version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: telegram-todo-bot
    restart: unless-stopped
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - DATA_FILE=/app/data/tasks.json
    
    # Volume for persistent data
    volumes:
      - bot_data:/app/data
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'

# Named volumes for data persistence
volumes:
  bot_data:
    driver: local
